# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  vmImageName: 'ubuntu-latest'

trigger:
- none

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Build
    displayName: Build Image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
        - task: Docker@2
          displayName: Build&Push secret-share-client
          inputs:
            containerRegistry: 'my-dockerhub'
            repository: 'ahmedavid/secret-share-client'
            command: 'buildAndPush'
            Dockerfile: '**/client/Dockerfile'
            tags: |
              $(Build.BuildId)
              latest
        - bash: ls -al
        - task: KubernetesManifest@0
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: 'kube-sc'
            namespace: 'default'
            manifests: |
              $(Pipeline.Workspace)/infra/k8s/client.yaml
