# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  vmImageName: 'ubuntu-latest'

trigger:
- main

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Build
    displayName: Build Image
    jobs:
      - job: Build
        displayName: Build
        pool: $(vmImageName)
        steps:
        - task: Docker@2
          displayName: Build&Push secret-share-client
          inputs:
            containerRegistry: 'my-dockerhub'
            repository: 'secret-share-client'
            command: 'buildAndPush'
            Dockerfile: '**/client/Dockerfile'
            tags: |
              $(Build.BuildId)
              'latest'
