# Use an official Nginx runtime as a parent image
FROM nginx:latest

# Copy all files from the current directory to the '/usr/share/nginx/html' directory in the container
COPY . /usr/share/nginx/html

# Expose port 80 to allow incoming traffic
EXPOSE 80